name: "streaming"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 256128
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5435:5432"
    expose:
      - 5432
    volumes:
      - "postgres:/data/db"

volumes:
  postgres:
